project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning for Econometricians"
  page-navigation: true
  sidebar:
    logo: logo.png
    style: "floating"
    search: true
    collapse-level: 0
    pinned: true
    contents:
    - section: "Background"
      contents: 
        - text: "1. Information Theory"
          href: information_theory.qmd
        - text: "2. Cross Validation"
          href: cross_validation.qmd
        - text: "3. Evaluating Predictive Distributions"
          href: evaluating_distributions.qmd
        - text: "4. Optimization for Machine Learning"
          href: optimization.qmd
    - section: "Neural Networks"
      contents:
        - text: "5. Feed-Forward Neural Networks"
          href: feed_forward_nns.qmd
        - text: "6. Recurrent Neural Networks"
          href: recurrent_neural_networks.qmd
        - text: "7. LSTM Networks"
          href: lstm_neural_networks.qmd
        - text: "8. Empirical Exercise: Networks for Time Series"
          href: nn_example.qmd
        - text: "9. Distribution Modeling with Neural Networks"
          href: distributions_via_nns.qmd
    - section: "Tree-Based Methods"
      contents:
        - text: "10. Decision Trees"
          href: decision_trees.qmd
        - text: "11. Random Forests"
          href: random_forests.qmd
        - text: "12. Gradient Boosting"
          href: gradient_boosting.qmd
        - text: "13. Advanced Tree-Based Methods"
          href: adv_tree_based_methods.qmd
    - section: "Further Topics"
      contents:
        - text: "14. Advanced Hyperparameter Optimization"
          href: hpo.qmd
        - text: "15. Conformal Prediction"
          href: conformal_prediction.qmd
        - text: "16. Foundation Models for Economic Text"
          href: foundation_models.qmd
        - text: "17. Data Sets Used in This Book"
          href: datasets.qmd
  page-footer: "Copyright 2025, Onno Kleen" 

bibliography: '/Users/onnokleen/Dropbox (Personal)/library.bib'
biblio-style: apalike
link-citations: true
links-as-notes: true

crossref:
  chapters: true

format:
  html:
    theme: 
      - cosmo
    css: styles.css
    code-fold: true
    code-summary: "Show the code"
    toc: true
    section-divs: true
    number-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
 
execute:
  cache: true
